#index:
#    path: /
#    controller: App\Controller\DefaultController::index
especialidades:
    path: /especialidades
    controller: App\Controller\EspecialidadesController::buscarTodos
    methods:
        - GET
especialidade:
    path: /especialidades/{id}
    controller: App\Controller\EspecialidadesController::buscarUm
    methods:
        - GET
nova_especialidade:
    path: /especialidades
    controller: App\Controller\EspecialidadesController::novo
    methods:
        - POST
remove_especialidade:
    path: /especialidades/{id}
    controller: App\Controller\EspecialidadesController::remove
    methods:
        - DELETE
atualiza_especialidade:
    path: /especialidades/{id}
    controller: App\Controller\EspecialidadesController::atualiza
    methods:
        - PUT

medicos:
    path: /medicos
    controller: App\Controller\MedicosController::buscarTodos
    methods:
        - GET
medico:
    path: /medicos/{id}
    controller: App\Controller\MedicosController::buscarUm
    methods:
        - GET
novo_medico:
    path: /medicos
    controller: App\Controller\MedicosController::novo
    methods:
        - POST
remove_medico:
    path: /medicos/{id}
    controller: App\Controller\MedicosController::remove
    methods:
        - DELETE
atualiza_medico:
    path: /medicos/{id}
    controller: App\Controller\MedicosController::atualiza
    methods:
        - PUT